### ISSUE TITLE
'.VBScript could not run." error on run.

### ISSUE THREAD

**Issue by FxllenCode** [LateralLines/delete-rbx-uieditor#1]
Whenever you run it, it ends up with that error. I did change the code a bit, here is what I did:

Command.cmd code:
```
    del /s "%localappdata%\Roblox\Versions\AlignmentTool*"
    del /s "%localappdata%\Roblox\Versions\AnimationClipEditor*"
    del /s "%localappdata%\Roblox\Versions\AvatarImporter*"
    del /s "%localappdata%\Roblox\Versions\LocalizationTools*"
    del /s "%localappdata%\Roblox\Versions\RigBuilder*"
```

Source.bat code:
```
    @echo off
    :loop
    del /s "%localappdata%\Roblox\Versions\AlignmentTool*"
    del /s "%localappdata%\Roblox\Versions\AnimationClipEditor*"
    del /s "%localappdata%\Roblox\Versions\AvatarImporter*"
    del /s "%localappdata%\Roblox\Versions\LocalizationTools*"
    del /s "%localappdata%\Roblox\Versions\RigBuilder*"
    timeout /t 15
    goto loop
```

Everything else remains the same.

**Comment by LateralLines** [comment]
Your modifications shouldn't be too much of an issue, so long as you didn't move the files or the root directory around. Make sure that when applying an action to the task you place the "wscript" command and its arguments into different fields. Here's an example:

Program/script --> wscript
Add arguments --> "C:\Path\To\Resources\init.vbs" "C:\Path\To\Resources\Source.bat"

My apologies for not explicitly stating this in my guide. Should have it updated soon. If that was not the issue, let me know what you got for the Last Run Result exit code in the Task Scheduler Library (click on folder under Task Scheduler (Local) on the far left panel and scroll right until you see this).
